### ISSUE TITLE
Screens not found

### ISSUE THREAD

**Issue by bryanberger** [arciisine/active-win#2]
```
Unhandled Exception: System.Exception: Screens not found
   at WinInfo.Utils.getScreens(RECT bounds)
   at WinInfo.Entrypoint.Main(String[] args)
```

Windows 10.
I believe this happens if the window is minimized when calling:
`console.log(winInfo.getByPidSync(PID_HERE));`

**Comment by arciisine** [comment]
Definitely not a scenario I planned for.  I'm assuming an error is potentially valid here.  What shape of response were you expecting?

**Comment by bryanberger** [comment]
I actually don't need the `screens[]` return, just the window info so I wasn't initially expecting an error. Going to fork and remove that complexity, figured i'd let you know about this edge case tho.

**Comment by arciisine** [comment]
Realistically, that could easily be worked into the lib, allowing the screen info to be optional.  The challenge for me is making sure it works consistently in a cross platform manner.  Thanks for the feedback!

**Comment by bryanberger** [comment]
100% -- I kinda needed this in a pinch (hence the removal route), it would make a good feature though for sure . Thanks for making this!
